import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { NavBar } from "@/components/nav-bar";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "RSC Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen flex-col dark antialiased",
          inter.variable
        )}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
